-- Use this file to define your SQL tables
-- The SQL in this file will be executed when you run `npm run setup-db`
DROP TABLE IF EXISTS users CASCADE;
DROP TABLE IF EXISTS prompts;

CREATE TABLE users (
  id BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
  email VARCHAR,
  password_hash VARCHAR NOT NULL,
  character_name VARCHAR NOT NULL,
  current_story_id INT
);

CREATE TABLE prompts (
  id BIGINT PRIMARY KEY,
  story VARCHAR NOT NULL,
  prompt_a VARCHAR NOT NULL,
  prompt_b VARCHAR NOT NULL,
  bailout VARCHAR NOT NULL,
  a_id INT NOT NULL,
  b_id INT NOT NULL,
  bail_id INT
);

INSERT INTO prompts (id, story, prompt_a, prompt_b, bailout, a_id, b_id, bail_id) 
VALUES 
(1, 'Good morning and what another sunny day. You have had a filling breakfast, a nice morning with your family and are about to get ready for work when... What is that sound? You rush to the bathroom and your toilet is spouting water everywhere! The knob at the wall is completely seized and will not turn! Running to the basement you quickly get the water turned off at the main. The flooding upstairs subsides before finally stopping. What do you do from here?', 'I am going to stay home and handle the plumber visit.', 'I am heading to work, my partner handles things like this for us.', 'Save My Game', 2, 3, 0),
(2, 'After choosing home you call the plumber. They say you are on the roster, but it will be a few hours. How will you occupy the meantime?', 'My team at work relies on me, I have the option, I am going to work from home.', 'My team can survive without me, I am going to stay off the computer.', 'Save My Game', 7, 6, 0),
(3, 'Having a reliable partner for things like this is such a gift. After getting in the car you come to the thought of all the water kind of wore you out. With your semi-flexible start time would you like to get coffee on the way to work?', 'A nice cup of coffee would be great right now.', 'I am already later than my normal arrival, I am going straight to work.', 'Save My Game', 4, 5, 0),
(4, 'That cup of coffee has really hit the spot! You have a couple different options of how to get to work from here, one is faster, but the other definitely looks a lot nicer, which way do you take?', 'I will head straight in to work.', 'I think I will take the pretty way today.', 'Save My Game', 5, 35, 0),
(5, 'With a delightfully uneventful drive you have now arrived at work! This time of day you and your coworkers frequently break for water and snacks. Do you head for the breakroom to check in or straight for your desk?', 'I head to the breakroom, then I can tell them about my morning and they can fill me in on what is happening here.', 'I am going to just go straight to my desk.', 'Save My Game', 13, 20, 0),
(6, 'Having a team who can operate without you can be such a relief. It has been quite a morning and they all understand. Are you going to do something productive here at home or just relax and watch some TV while waiting for the plumber?', 'I have the house to myself, I should be productive with this time.', 'Today has already been a lot and will be even more once the plumber arrives. I am watching Netflix.', 'Save My Game', 8, 9, 0),
(7, 'Being a dependable teammate is both a blessing and a curse. Do you start your day by reading some news or checking your email?', 'I like to keep informed, lets read the news.', 'I like to get straight into work, let''s check my email.', 'Save My Game', 10, 20, 0),
(8, 'You and your partner keep a ranked task list together. The two most pressing items are the huge laundry backlog and the financial plan for next month, what do you choose?', 'Tackling Laundry is going to be simpler, to the laundry room!', 'Sounds like it is time to tackle some bills.', 'Save My Game', 11, 12, 0),
(9, 'Sitting down at your tv your Netflix has two good sounding recommendations on what to watch next, Bandersnatch, a 1980s slanted choose your own adventure, or the next episode of Our Universe, a nature documentary you have been watching.', 'Our Universe', 'Bandersnatch', 'Save My Game', 14, 15, 0),
(10, 'The top story today covers a new breakthrough in AI. MIT has now built a learning AI that can pass the Turing test. How do you react?', 'This is a major leap for us. I cannot wait to see what happens next.', 'This might be a step too far.', 'Save My Game', 16, 17, 0),
(11, 'After sorting for your first load of laundry and loading it into the washer you pause. Wait. The water is off. Laundry cannot happen. You need a break.', 'Netflix it is after all.', 'I think going outside for some fresh air sounds like a nice change.', 'Save My Game', 9, 23, 0),
(12, 'You have gotten everything together. All your monthly bills, the expenses for a couple known extras over the next month, but wait, what about the plumbing bill from today? You need a break.', 'Netflix it is after all.', 'I think going outside for some fresh air sounds like a nice change.', 'Save My Game', 9, 23, 0),
(13, 'Everyone in the breakroom is clustered around someone new! It feels a little crazy but... are they green? Not wearing green but they literally have green skin. How is no one else noticing?', 'I am calling my cousin at the NSA, maybe its paranoia but I would rather be safe.', 'Maybe I am just seeing things. This is no big deal.', 'Save My Game', 18, 19, 0),
(14, 'Sometimes outdoor documentaries really remind you just how small the world around us truly is. Some fresh air right now would be great.', 'Front porch rocker sounds lovely right about now.', 'The privacy of my backyard sounds great.', 'Save My Game', 22, 23, 0),
(15, 'About 45 minutes into Bandersnatch you are startled as your phone rings. Pausing the show you see work is calling. Do you answer?', 'They already know I am taking the day, they can go on without me.', 'Well, they know not call unless it is dire, you answer the call.', 'Save My Game', 25, 26, 0),
(16, 'Unchecked, AI continues to advance at an alarming rate. Over the next 10 years AI has surpassed humans in the workforce and has taken over 90% of government decisions. We have entered the age of AI, and ended the age of humanity.', 'Go back to the news', 'Start a New Day', 'Exit', 10, 1, 0),
(17, 'Sometimes a healthy dose of skepticism about advancement is probably good. Is that the dooorbell?', 'It could be solicitors, I am going to check my email instead.', 'It could be the plumber! I am getting the door.', 'Save My Game', 21, 20, 0),
(18, 'Your cousin thanks you for your service and hangs up. What in the world?? You have had odd conversations before but this one takes the cake. Then nothing. Your cousin has bombed your office. In the following weeks it comes out that the government was hiding a known alien invasion. The World devolves to chaos.', 'Go back to the breakroom', 'Start a New Day', 'Exit', 13, 1, 0),
(19, 'The day ends and all is fine as far as you know. The world turns. You slowly begin to notice more and more people like your mystery coworker. Then one day, you realize every world leader is green. The world has been taken over by Aliens.', 'Go back to the breakroom', 'Start a New Day', 'Exit', 13, 1, 0),
(20, 'After opening your computer You have two really interesting emails. You are being invited to join two different special teams at work! The first is very similar to what you do now, no real challenge. The second requires quite a few new skills for you, the leaders have the confidence you can build them but you are a bit more uneasy. Which do you choose?', 'The first, I am in the headspace of a simple work through.', 'The second, they believe in me so bring it on!', 'Save My Game', 28, 27, 0),
(21, 'The plumber is here! After 3 hours and $400 dollars later the plumber has repaired the toilet. They found the toddler had shoved several toys down the toilet. Well. Tomorrow is a new day.', 'Go back to the computer', 'Start a New Day', 'Exit', 17, 1, 0),
(22, 'What great timing! The plumber is here! After 3 hours and $400 dollars later the plumber has repaired the toilet. They found the toddler had shoved several toys down the toilet. Well. Tomorrow is a new day.', 'Go back to the documentary', 'Start a New Day', 'Exit', 14, 1, 0),
(23, 'What a wonderful breeze. Going outside is like all the stress is melting away. A quick walk through the neighborhood should be okay... The plumber is supposed to call when they are 10 minutes away. Or maybe you should crawl in the hammock. The gentle sway of the breeze makes it look awfully enticing.', 'A quick walk through the neighborhood, this is probably the only time I can squeeze this in today.', 'Going away from the house is too big a risk. I am getting in the hammock.', 'Save My Game', 24, 29, 0),
(24, 'What a nice stroll through the neighborhood! Walking up to the door you see a slip, oh no! The plumber never called and you missed them! Calling back they can get you on the roster again. With an appointment first thing in the morning. Well, I guess tomorrow is a new day.', 'Go back to the backyard', 'Start a New Day', 'Exit', 23, 1, 0),
(25, 'Pausing made you realize just how anxious Bandersnatch was making you, and just how hungry you were getting. What do you eat?', 'Ice Cream, this morning has been a lot and no one is home to judge you so why not?', 'Grilled Cheese, sometimes the meltiness is just what is needed.', 'Save My Game', 32, 33, 0),
(26, 'You answer the phone, something has come up that only you have the access to solve. After logging in to your work computer and solving the issue do you check your work email or read the news?', 'Might as well check my email.', 'I think a break for the news sounds great.', 'Save My Game', 20, 10, 0),
(27, 'Well, they believe in you so fortune favors the bold? 30 years later it proves to be true. Your project somehow created a utopia? Congratulations on a job well done?', 'Go back to picking an Email', 'Start a New Day', 'Exit', 20, 1, 0),
(28, 'Taking a known project is a comfortable place. That leads to more comfortable places. This comfortable place helps usher in a way to retrofit gas cars for self driving. As a side effect you have now destroyed the O-Zone. But hey! Self driving cars!', 'Go back to picking an email', 'Start a New Day', 'Exit', 20, 1, 0),
(29, 'Oh the hammock was such a good choice. The gentle breeze is slowly pushing you back and forth, back and forth...', 'I have to get out of this thing, I could fall asleep.', '...zZzz...', 'Save My Game', 34, 30, 0),
(30, 'You wake up to the sun having moved and a note on the door. You missed the plumber. Calling back they can get you on the roster again. With an appointment first thing in the morning. Well, I guess tomorrow is a new day.', 'Go back to the hammock.', 'Start a New Day', 'Exit', 29, 1, 0),
(31, 'The plumber is here! After 3 hours and $400 dollars later the plumber has repaired the toilet. They found the toddler had shoved several toys down the toilet. Well. Tomorrow is a new day.', 'Go back to the Ice Cream', 'Start a New Day', 'Exit', 32, 1, 0),
(32, 'A bite to eat is just what you needed. That ice cream really hit the spot. Wait now both your phone is ringing again and the doorbell is going off. What do you choose?', 'They are calling a second time? I should probably answer.', 'It could be solicitors... or it could be the plumber! I have to get the door.', 'Save My Game', 26, 31, 0),
(33, 'A bite to eat is just what you needed. That grilled cheese really hit the spot. Wait now both your phone is ringing again and the doorbell is going off. What do you choose?', 'They are calling a second time? I should probably answer.', 'It could be solicitors... or it could be the plumber! I have to get the door.', 'Save My Game', 26, 31, 0),
(34, 'You hear the bell ringing... the plumber is here! After 3 hours and $400 dollars later the plumber has repaired the toilet. They found the toddler had shoved several toys down the toilet. Well. Tomorrow is a new day.', 'Go back to the hammock.', 'Start a New Day', 'Exit', 29, 1, 0),
(35, 'The path is full of curves but you are having a lovely drive. After the next corner you slam on the brakes. Skidding a bit, you safely come to a halt. The road in front of you is completely covered. The hillside above has come loose and the road is gone.', 'Turn back', 'Start a New Day', 'Exit', 4, 1, 0),
(36, 'The plumber is here! After 3 hours and $400 dollars later the plumber has repaired the toilet. They found the toddler had shoved several toys down the toilet. Well. Tomorrow is a new day.', 'Go back to the Ice Grilled Cheese', 'Start a New Day', 'Exit', 33, 1, 0);